##
# Bounce
#
# @file
# @version 0.1

all:
	cc -o particles particles.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
run:
	cc -o particles particles.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 && ./particles

# end
